declare interface githubLatest {
  url: URL
  assets_url: URL
  upload_url: URL
  html_url: URL
  id: number
  author: {
    login: string
    id: number
    node_id: string
    avatar_url: URL
    gravatar_id: string
    url: URL
    html_url: URL
    followers_url: URL
    following_url: URL
    gists_url: URL
    starred_url: URL
    subscriptions_url: URL
    organizations_url: URL
    repos_url: URL
    events_url: URL
    received_events_url: URL
    type: string
    site_admin: boolean
  }
  node_id: string
  tag_name: string
  target_commitish: string
  name: string
  draft: boolean
  prerelease: boolean
  created_at: Date
  published_at: Date
  assets: {
    url: URL
    id: string
    node_id: string
    name: string
    label: string
    uploader: {
      login: string
      id: number
      node_id: string
      avatar_url: URL
      gravatar_id: string
      url: URL
      html_url: URL
      followers_url: URL
      following_url: URL
      gists_url: URL
      starred_url: URL
      subscriptions_url: URL
      organizations_url: URL
      repos_url: URL
      events_url: URL
      received_events_url: string
      type: string
      site_admin: boolean
    }
    content_type: string
    state: string
    size: number
    download_count: number
    created_at: Date
    updated_at: Date
    browser_download_url: URL
  }[]
  tarball_url: string
  zipball_url: string
  body: string
  discussion_url: string
}
