export { default as Get } from './get'
export { default as Put } from './put'
export { default as Patch } from './patch'
export { default as Delete } from './delete'
export { default as Post } from './post'
